# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'PrototypeIosObjC' do
pod 'PebbleKit'
end

target 'PrototypeIosObjCTests' do
pod 'PebbleKit'
pod 'OCMock'
end

